# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget

from tkinter import *
from tkinter import filedialog
import copy

import saveMessage
import LoadandSave

class Ui_preview(QWidget):
    def setupUi(self, preview):
        preview.setObjectName("preview")
        preview.resize(930, 780)
        preview.setMinimumSize(QtCore.QSize(930, 780))
        self.centralwidget = QtWidgets.QWidget(preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(930, 730))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(22, 11, 891, 716))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.first = QtWidgets.QLabel(self.widget)
        self.first.setObjectName("first")
        self.verticalLayout_7.addWidget(self.first)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.first_name = QtWidgets.QLabel(self.frame)
        self.first_name.setObjectName("first_name")
        self.verticalLayout.addWidget(self.first_name)
        self.lineEdit_first_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_name.setReadOnly(True)
        self.lineEdit_first_name.setObjectName("lineEdit_first_name")
        self.verticalLayout.addWidget(self.lineEdit_first_name)
        self.first_level = QtWidgets.QLabel(self.frame)
        self.first_level.setObjectName("first_level")
        self.verticalLayout.addWidget(self.first_level)
        self.lineEdit_first_level = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_level.setReadOnly(True)
        self.lineEdit_first_level.setObjectName("lineEdit_first_level")
        self.verticalLayout.addWidget(self.lineEdit_first_level)
        self.first_hp = QtWidgets.QLabel(self.frame)
        self.first_hp.setObjectName("first_hp")
        self.verticalLayout.addWidget(self.first_hp)
        self.lineEdit_first_hp = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_hp.setReadOnly(True)
        self.lineEdit_first_hp.setObjectName("lineEdit_first_hp")
        self.verticalLayout.addWidget(self.lineEdit_first_hp)
        self.first_pow = QtWidgets.QLabel(self.frame)
        self.first_pow.setObjectName("first_pow")
        self.verticalLayout.addWidget(self.first_pow)
        self.lineEdit_first_pow = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_pow.setReadOnly(True)
        self.lineEdit_first_pow.setObjectName("lineEdit_first_pow")
        self.verticalLayout.addWidget(self.lineEdit_first_pow)
        self.first_dodge = QtWidgets.QLabel(self.frame)
        self.first_dodge.setObjectName("first_dodge")
        self.verticalLayout.addWidget(self.first_dodge)
        self.lineEdit_first_dodge = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_dodge.setReadOnly(True)
        self.lineEdit_first_dodge.setObjectName("lineEdit_first_dodge")
        self.verticalLayout.addWidget(self.lineEdit_first_dodge)
        self.first_rate = QtWidgets.QLabel(self.frame)
        self.first_rate.setObjectName("first_rate")
        self.verticalLayout.addWidget(self.first_rate)
        self.lineEdit_first_rate = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_rate.setReadOnly(True)
        self.lineEdit_first_rate.setObjectName("lineEdit_first_rate")
        self.verticalLayout.addWidget(self.lineEdit_first_rate)
        self.first_hit = QtWidgets.QLabel(self.frame)
        self.first_hit.setObjectName("first_hit")
        self.verticalLayout.addWidget(self.first_hit)
        self.lineEdit_first_hit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_hit.setReadOnly(True)
        self.lineEdit_first_hit.setObjectName("lineEdit_first_hit")
        self.verticalLayout.addWidget(self.lineEdit_first_hit)
        self.first_number = QtWidgets.QLabel(self.frame)
        self.first_number.setObjectName("first_number")
        self.verticalLayout.addWidget(self.first_number)
        self.lineEdit_first_number = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_number.setReadOnly(True)
        self.lineEdit_first_number.setObjectName("lineEdit_first_number")
        self.verticalLayout.addWidget(self.lineEdit_first_number)
        self.first_skill_1 = QtWidgets.QLabel(self.frame)
        self.first_skill_1.setObjectName("first_skill_1")
        self.verticalLayout.addWidget(self.first_skill_1)
        self.lineEdit_first_skill_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_skill_1.setReadOnly(True)
        self.lineEdit_first_skill_1.setObjectName("lineEdit_first_skill_1")
        self.verticalLayout.addWidget(self.lineEdit_first_skill_1)
        self.first_skill_2 = QtWidgets.QLabel(self.frame)
        self.first_skill_2.setObjectName("first_skill_2")
        self.verticalLayout.addWidget(self.first_skill_2)
        self.lineEdit_first_skill_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_skill_2.setReadOnly(True)
        self.lineEdit_first_skill_2.setObjectName("lineEdit_first_skill_2")
        self.verticalLayout.addWidget(self.lineEdit_first_skill_2)
        self.first_favor = QtWidgets.QLabel(self.frame)
        self.first_favor.setObjectName("first_favor")
        self.verticalLayout.addWidget(self.first_favor)
        self.lineEdit_first_favor = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_favor.setReadOnly(True)
        self.lineEdit_first_favor.setObjectName("lineEdit_first_favor")
        self.verticalLayout.addWidget(self.lineEdit_first_favor)
        self.first_position = QtWidgets.QLabel(self.frame)
        self.first_position.setObjectName("first_position")
        self.verticalLayout.addWidget(self.first_position)
        self.lineEdit_first_position = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_first_position.setReadOnly(True)
        self.lineEdit_first_position.setObjectName("lineEdit_first_position")
        self.verticalLayout.addWidget(self.lineEdit_first_position)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.second = QtWidgets.QLabel(self.widget)
        self.second.setObjectName("second")
        self.verticalLayout_8.addWidget(self.second)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.second_name = QtWidgets.QLabel(self.frame_2)
        self.second_name.setObjectName("second_name")
        self.verticalLayout_2.addWidget(self.second_name)
        self.lineEdit_second_name = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_name.setReadOnly(True)
        self.lineEdit_second_name.setObjectName("lineEdit_second_name")
        self.verticalLayout_2.addWidget(self.lineEdit_second_name)
        self.second_level = QtWidgets.QLabel(self.frame_2)
        self.second_level.setObjectName("second_level")
        self.verticalLayout_2.addWidget(self.second_level)
        self.lineEdit_second_level = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_level.setReadOnly(True)
        self.lineEdit_second_level.setObjectName("lineEdit_second_level")
        self.verticalLayout_2.addWidget(self.lineEdit_second_level)
        self.second_hp = QtWidgets.QLabel(self.frame_2)
        self.second_hp.setObjectName("second_hp")
        self.verticalLayout_2.addWidget(self.second_hp)
        self.lineEdit_second_hp = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_hp.setReadOnly(True)
        self.lineEdit_second_hp.setObjectName("lineEdit_second_hp")
        self.verticalLayout_2.addWidget(self.lineEdit_second_hp)
        self.second_pow = QtWidgets.QLabel(self.frame_2)
        self.second_pow.setObjectName("second_pow")
        self.verticalLayout_2.addWidget(self.second_pow)
        self.lineEdit_second_pow = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_pow.setReadOnly(True)
        self.lineEdit_second_pow.setObjectName("lineEdit_second_pow")
        self.verticalLayout_2.addWidget(self.lineEdit_second_pow)
        self.second_dodge = QtWidgets.QLabel(self.frame_2)
        self.second_dodge.setObjectName("second_dodge")
        self.verticalLayout_2.addWidget(self.second_dodge)
        self.lineEdit_second_dodge = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_dodge.setReadOnly(True)
        self.lineEdit_second_dodge.setObjectName("lineEdit_second_dodge")
        self.verticalLayout_2.addWidget(self.lineEdit_second_dodge)
        self.second_rate = QtWidgets.QLabel(self.frame_2)
        self.second_rate.setObjectName("second_rate")
        self.verticalLayout_2.addWidget(self.second_rate)
        self.lineEdit_second_rate = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_rate.setReadOnly(True)
        self.lineEdit_second_rate.setObjectName("lineEdit_second_rate")
        self.verticalLayout_2.addWidget(self.lineEdit_second_rate)
        self.second_hit = QtWidgets.QLabel(self.frame_2)
        self.second_hit.setObjectName("second_hit")
        self.verticalLayout_2.addWidget(self.second_hit)
        self.lineEdit_second_hit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_hit.setReadOnly(True)
        self.lineEdit_second_hit.setObjectName("lineEdit_second_hit")
        self.verticalLayout_2.addWidget(self.lineEdit_second_hit)
        self.second_number = QtWidgets.QLabel(self.frame_2)
        self.second_number.setObjectName("second_number")
        self.verticalLayout_2.addWidget(self.second_number)
        self.lineEdit_second_number = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_number.setReadOnly(True)
        self.lineEdit_second_number.setObjectName("lineEdit_second_number")
        self.verticalLayout_2.addWidget(self.lineEdit_second_number)
        self.second_skill_1 = QtWidgets.QLabel(self.frame_2)
        self.second_skill_1.setObjectName("second_skill_1")
        self.verticalLayout_2.addWidget(self.second_skill_1)
        self.lineEdit_second_skill_1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_skill_1.setReadOnly(True)
        self.lineEdit_second_skill_1.setObjectName("lineEdit_second_skill_1")
        self.verticalLayout_2.addWidget(self.lineEdit_second_skill_1)
        self.second_skill_2 = QtWidgets.QLabel(self.frame_2)
        self.second_skill_2.setObjectName("second_skill_2")
        self.verticalLayout_2.addWidget(self.second_skill_2)
        self.lineEdit_second_skill_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_skill_2.setReadOnly(True)
        self.lineEdit_second_skill_2.setObjectName("lineEdit_second_skill_2")
        self.verticalLayout_2.addWidget(self.lineEdit_second_skill_2)
        self.second_favor = QtWidgets.QLabel(self.frame_2)
        self.second_favor.setObjectName("second_favor")
        self.verticalLayout_2.addWidget(self.second_favor)
        self.lineEdit_second_favor = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_favor.setReadOnly(True)
        self.lineEdit_second_favor.setObjectName("lineEdit_second_favor")
        self.verticalLayout_2.addWidget(self.lineEdit_second_favor)
        self.second_position = QtWidgets.QLabel(self.frame_2)
        self.second_position.setObjectName("second_position")
        self.verticalLayout_2.addWidget(self.second_position)
        self.lineEdit_second_position = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_second_position.setReadOnly(True)
        self.lineEdit_second_position.setObjectName("lineEdit_second_position")
        self.verticalLayout_2.addWidget(self.lineEdit_second_position)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.third = QtWidgets.QLabel(self.widget)
        self.third.setObjectName("third")
        self.verticalLayout_9.addWidget(self.third)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.third_name = QtWidgets.QLabel(self.frame_3)
        self.third_name.setObjectName("third_name")
        self.verticalLayout_3.addWidget(self.third_name)
        self.lineEdit_third_name = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_name.setReadOnly(True)
        self.lineEdit_third_name.setObjectName("lineEdit_third_name")
        self.verticalLayout_3.addWidget(self.lineEdit_third_name)
        self.third_level = QtWidgets.QLabel(self.frame_3)
        self.third_level.setObjectName("third_level")
        self.verticalLayout_3.addWidget(self.third_level)
        self.lineEdit_third_level = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_level.setReadOnly(True)
        self.lineEdit_third_level.setObjectName("lineEdit_third_level")
        self.verticalLayout_3.addWidget(self.lineEdit_third_level)
        self.third_hp = QtWidgets.QLabel(self.frame_3)
        self.third_hp.setObjectName("third_hp")
        self.verticalLayout_3.addWidget(self.third_hp)
        self.lineEdit_third_hp = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_hp.setReadOnly(True)
        self.lineEdit_third_hp.setObjectName("lineEdit_third_hp")
        self.verticalLayout_3.addWidget(self.lineEdit_third_hp)
        self.third_pow = QtWidgets.QLabel(self.frame_3)
        self.third_pow.setObjectName("third_pow")
        self.verticalLayout_3.addWidget(self.third_pow)
        self.lineEdit_third_pow = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_pow.setReadOnly(True)
        self.lineEdit_third_pow.setObjectName("lineEdit_third_pow")
        self.verticalLayout_3.addWidget(self.lineEdit_third_pow)
        self.third_dodge = QtWidgets.QLabel(self.frame_3)
        self.third_dodge.setObjectName("third_dodge")
        self.verticalLayout_3.addWidget(self.third_dodge)
        self.lineEdit_third_dodge = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_dodge.setReadOnly(True)
        self.lineEdit_third_dodge.setObjectName("lineEdit_third_dodge")
        self.verticalLayout_3.addWidget(self.lineEdit_third_dodge)
        self.third_rate = QtWidgets.QLabel(self.frame_3)
        self.third_rate.setObjectName("third_rate")
        self.verticalLayout_3.addWidget(self.third_rate)
        self.lineEdit_third_rate = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_rate.setReadOnly(True)
        self.lineEdit_third_rate.setObjectName("lineEdit_third_rate")
        self.verticalLayout_3.addWidget(self.lineEdit_third_rate)
        self.third_hit = QtWidgets.QLabel(self.frame_3)
        self.third_hit.setObjectName("third_hit")
        self.verticalLayout_3.addWidget(self.third_hit)
        self.lineEdit_third_hit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_hit.setReadOnly(True)
        self.lineEdit_third_hit.setObjectName("lineEdit_third_hit")
        self.verticalLayout_3.addWidget(self.lineEdit_third_hit)
        self.third_number = QtWidgets.QLabel(self.frame_3)
        self.third_number.setObjectName("third_number")
        self.verticalLayout_3.addWidget(self.third_number)
        self.lineEdit_third_number = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_number.setReadOnly(True)
        self.lineEdit_third_number.setObjectName("lineEdit_third_number")
        self.verticalLayout_3.addWidget(self.lineEdit_third_number)
        self.third_skill_1 = QtWidgets.QLabel(self.frame_3)
        self.third_skill_1.setObjectName("third_skill_1")
        self.verticalLayout_3.addWidget(self.third_skill_1)
        self.lineEdit_third_skill_1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_skill_1.setReadOnly(True)
        self.lineEdit_third_skill_1.setObjectName("lineEdit_third_skill_1")
        self.verticalLayout_3.addWidget(self.lineEdit_third_skill_1)
        self.third_skill_2 = QtWidgets.QLabel(self.frame_3)
        self.third_skill_2.setObjectName("third_skill_2")
        self.verticalLayout_3.addWidget(self.third_skill_2)
        self.lineEdit_third_skill_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_skill_2.setReadOnly(True)
        self.lineEdit_third_skill_2.setObjectName("lineEdit_third_skill_2")
        self.verticalLayout_3.addWidget(self.lineEdit_third_skill_2)
        self.third_favor = QtWidgets.QLabel(self.frame_3)
        self.third_favor.setObjectName("third_favor")
        self.verticalLayout_3.addWidget(self.third_favor)
        self.lineEdit_third_favor = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_favor.setReadOnly(True)
        self.lineEdit_third_favor.setObjectName("lineEdit_third_favor")
        self.verticalLayout_3.addWidget(self.lineEdit_third_favor)
        self.third_position = QtWidgets.QLabel(self.frame_3)
        self.third_position.setObjectName("third_position")
        self.verticalLayout_3.addWidget(self.third_position)
        self.lineEdit_third_position = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_third_position.setReadOnly(True)
        self.lineEdit_third_position.setObjectName("lineEdit_third_position")
        self.verticalLayout_3.addWidget(self.lineEdit_third_position)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.forth = QtWidgets.QLabel(self.widget)
        self.forth.setObjectName("forth")
        self.verticalLayout_10.addWidget(self.forth)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.forth_name = QtWidgets.QLabel(self.frame_4)
        self.forth_name.setObjectName("forth_name")
        self.verticalLayout_4.addWidget(self.forth_name)
        self.lineEdit_forth_name = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_name.setReadOnly(True)
        self.lineEdit_forth_name.setObjectName("lineEdit_forth_name")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_name)
        self.forth_level = QtWidgets.QLabel(self.frame_4)
        self.forth_level.setObjectName("forth_level")
        self.verticalLayout_4.addWidget(self.forth_level)
        self.lineEdit_forth_level = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_level.setReadOnly(True)
        self.lineEdit_forth_level.setObjectName("lineEdit_forth_level")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_level)
        self.forth_hp = QtWidgets.QLabel(self.frame_4)
        self.forth_hp.setObjectName("forth_hp")
        self.verticalLayout_4.addWidget(self.forth_hp)
        self.lineEdit_forth_hp = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_hp.setReadOnly(True)
        self.lineEdit_forth_hp.setObjectName("lineEdit_forth_hp")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_hp)
        self.forth_pow = QtWidgets.QLabel(self.frame_4)
        self.forth_pow.setObjectName("forth_pow")
        self.verticalLayout_4.addWidget(self.forth_pow)
        self.lineEdit_forth_pow = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_pow.setReadOnly(True)
        self.lineEdit_forth_pow.setObjectName("lineEdit_forth_pow")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_pow)
        self.forth_dodge = QtWidgets.QLabel(self.frame_4)
        self.forth_dodge.setObjectName("forth_dodge")
        self.verticalLayout_4.addWidget(self.forth_dodge)
        self.lineEdit_forth_dodge = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_dodge.setReadOnly(True)
        self.lineEdit_forth_dodge.setObjectName("lineEdit_forth_dodge")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_dodge)
        self.forth_rate = QtWidgets.QLabel(self.frame_4)
        self.forth_rate.setObjectName("forth_rate")
        self.verticalLayout_4.addWidget(self.forth_rate)
        self.lineEdit_forth_rate = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_rate.setReadOnly(True)
        self.lineEdit_forth_rate.setObjectName("lineEdit_forth_rate")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_rate)
        self.forth_hit = QtWidgets.QLabel(self.frame_4)
        self.forth_hit.setObjectName("forth_hit")
        self.verticalLayout_4.addWidget(self.forth_hit)
        self.lineEdit_forth_hit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_hit.setReadOnly(True)
        self.lineEdit_forth_hit.setObjectName("lineEdit_forth_hit")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_hit)
        self.forth_number = QtWidgets.QLabel(self.frame_4)
        self.forth_number.setObjectName("forth_number")
        self.verticalLayout_4.addWidget(self.forth_number)
        self.lineEdit_forth_number = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_number.setReadOnly(True)
        self.lineEdit_forth_number.setObjectName("lineEdit_forth_number")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_number)
        self.forth_skill_1 = QtWidgets.QLabel(self.frame_4)
        self.forth_skill_1.setObjectName("forth_skill_1")
        self.verticalLayout_4.addWidget(self.forth_skill_1)
        self.lineEdit_forth_skill_1 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_skill_1.setReadOnly(True)
        self.lineEdit_forth_skill_1.setObjectName("lineEdit_forth_skill_1")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_skill_1)
        self.forth_skill_2 = QtWidgets.QLabel(self.frame_4)
        self.forth_skill_2.setObjectName("forth_skill_2")
        self.verticalLayout_4.addWidget(self.forth_skill_2)
        self.lineEdit_forth_skill_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_skill_2.setReadOnly(True)
        self.lineEdit_forth_skill_2.setObjectName("lineEdit_forth_skill_2")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_skill_2)
        self.forth_favor = QtWidgets.QLabel(self.frame_4)
        self.forth_favor.setObjectName("forth_favor")
        self.verticalLayout_4.addWidget(self.forth_favor)
        self.lineEdit_forth_favor = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_favor.setReadOnly(True)
        self.lineEdit_forth_favor.setObjectName("lineEdit_forth_favor")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_favor)
        self.forth_position = QtWidgets.QLabel(self.frame_4)
        self.forth_position.setObjectName("forth_position")
        self.verticalLayout_4.addWidget(self.forth_position)
        self.lineEdit_forth_position = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_forth_position.setReadOnly(True)
        self.lineEdit_forth_position.setObjectName("lineEdit_forth_position")
        self.verticalLayout_4.addWidget(self.lineEdit_forth_position)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_4)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.fifth = QtWidgets.QLabel(self.widget)
        self.fifth.setObjectName("fifth")
        self.verticalLayout_11.addWidget(self.fifth)
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fifth_name = QtWidgets.QLabel(self.frame_5)
        self.fifth_name.setObjectName("fifth_name")
        self.verticalLayout_6.addWidget(self.fifth_name)
        self.lineEdit_fifth_name = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_name.setReadOnly(True)
        self.lineEdit_fifth_name.setObjectName("lineEdit_fifth_name")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_name)
        self.fifth_level = QtWidgets.QLabel(self.frame_5)
        self.fifth_level.setObjectName("fifth_level")
        self.verticalLayout_6.addWidget(self.fifth_level)
        self.lineEdit_fifth_level = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_level.setReadOnly(True)
        self.lineEdit_fifth_level.setObjectName("lineEdit_fifth_level")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_level)
        self.fifth_hp = QtWidgets.QLabel(self.frame_5)
        self.fifth_hp.setObjectName("fifth_hp")
        self.verticalLayout_6.addWidget(self.fifth_hp)
        self.lineEdit_fifth_hp = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_hp.setReadOnly(True)
        self.lineEdit_fifth_hp.setObjectName("lineEdit_fifth_hp")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_hp)
        self.fifth_pow = QtWidgets.QLabel(self.frame_5)
        self.fifth_pow.setObjectName("fifth_pow")
        self.verticalLayout_6.addWidget(self.fifth_pow)
        self.lineEdit_fifth_pow = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_pow.setReadOnly(True)
        self.lineEdit_fifth_pow.setObjectName("lineEdit_fifth_pow")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_pow)
        self.fifth_dodge = QtWidgets.QLabel(self.frame_5)
        self.fifth_dodge.setObjectName("fifth_dodge")
        self.verticalLayout_6.addWidget(self.fifth_dodge)
        self.lineEdit_fifth_dodge = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_dodge.setReadOnly(True)
        self.lineEdit_fifth_dodge.setObjectName("lineEdit_fifth_dodge")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_dodge)
        self.fifth_rate = QtWidgets.QLabel(self.frame_5)
        self.fifth_rate.setObjectName("fifth_rate")
        self.verticalLayout_6.addWidget(self.fifth_rate)
        self.lineEdit_fifth_rate = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_rate.setReadOnly(True)
        self.lineEdit_fifth_rate.setObjectName("lineEdit_fifth_rate")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_rate)
        self.fifth_hit = QtWidgets.QLabel(self.frame_5)
        self.fifth_hit.setObjectName("fifth_hit")
        self.verticalLayout_6.addWidget(self.fifth_hit)
        self.lineEdit_fifth_hit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_hit.setReadOnly(True)
        self.lineEdit_fifth_hit.setObjectName("lineEdit_fifth_hit")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_hit)
        self.fifth_number = QtWidgets.QLabel(self.frame_5)
        self.fifth_number.setObjectName("fifth_number")
        self.verticalLayout_6.addWidget(self.fifth_number)
        self.lineEdit_fifth_number = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_number.setReadOnly(True)
        self.lineEdit_fifth_number.setObjectName("lineEdit_fifth_number")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_number)
        self.fifth_skill_1 = QtWidgets.QLabel(self.frame_5)
        self.fifth_skill_1.setObjectName("fifth_skill_1")
        self.verticalLayout_6.addWidget(self.fifth_skill_1)
        self.lineEdit_fifth_skill_1 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_skill_1.setReadOnly(True)
        self.lineEdit_fifth_skill_1.setObjectName("lineEdit_fifth_skill_1")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_skill_1)
        self.fifth_skill_2 = QtWidgets.QLabel(self.frame_5)
        self.fifth_skill_2.setObjectName("fifth_skill_2")
        self.verticalLayout_6.addWidget(self.fifth_skill_2)
        self.lineEdit_fifth_skill_2 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_skill_2.setReadOnly(True)
        self.lineEdit_fifth_skill_2.setObjectName("lineEdit_fifth_skill_2")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_skill_2)
        self.fifth_favor = QtWidgets.QLabel(self.frame_5)
        self.fifth_favor.setObjectName("fifth_favor")
        self.verticalLayout_6.addWidget(self.fifth_favor)
        self.lineEdit_fifth_favor = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_favor.setReadOnly(True)
        self.lineEdit_fifth_favor.setObjectName("lineEdit_fifth_favor")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_favor)
        self.fifth_position = QtWidgets.QLabel(self.frame_5)
        self.fifth_position.setObjectName("fifth_position")
        self.verticalLayout_6.addWidget(self.fifth_position)
        self.lineEdit_fifth_position = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_fifth_position.setReadOnly(True)
        self.lineEdit_fifth_position.setObjectName("lineEdit_fifth_position")
        self.verticalLayout_6.addWidget(self.lineEdit_fifth_position)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.setting = QtWidgets.QLabel(self.widget)
        self.setting.setObjectName("setting")
        self.verticalLayout_5.addWidget(self.setting)
        self.frame_6 = QtWidgets.QFrame(self.widget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.saveBtn = QtWidgets.QPushButton(self.frame_6)
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout_12.addWidget(self.saveBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem)
        self.cancelBtn = QtWidgets.QPushButton(self.frame_6)
        self.cancelBtn.setObjectName("cancelBtn")
        self.verticalLayout_12.addWidget(self.cancelBtn)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        preview.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(preview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        preview.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(preview)
        self.statusbar.setObjectName("statusbar")
        preview.setStatusBar(self.statusbar)
        self.actionload = QtWidgets.QAction(preview)
        self.actionload.setObjectName("actionload")
        self.actionsave = QtWidgets.QAction(preview)
        self.actionsave.setObjectName("actionsave")
        self.menufile.addAction(self.actionload)
        self.menufile.addAction(self.actionsave)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(preview)
        QtCore.QMetaObject.connectSlotsByName(preview)

        self.actionload.setShortcut('ctrl+L')
        self.actionsave.setShortcut('ctrl+S')

        self.actionsave.triggered.connect(saveBtn_clicked)
        self.actionload.triggered.connect(self.loadFile)

        self.saveBtn.clicked.connect(saveBtn_clicked)
        self.cancelBtn.clicked.connect(cancelBtn_clicked)

    def loadFile(self):
        root = Tk()
        root.filename = filedialog.askopenfilename(initialdir="E:/Images", title="choose your file",
                                                   filetypes=(("gun files", "*.gun"), ("all files", "*.*")))
        try:
            global data
            data = LoadandSave.load(root.filename).get()
        except:
            pass

        root.withdraw()

        try:
            self.lineEdit_first_name.setText(str(data["gun1"]["gun_id"]))
            self.lineEdit_first_level.setText(str(data["gun1"]["gun_level"]))
            self.lineEdit_first_hp.setText(str(data["gun1"]["life"]))
            self.lineEdit_first_pow.setText(str(data["gun1"]["pow"]))
            self.lineEdit_first_dodge.setText(str(data["gun1"]["dodge"]))
            self.lineEdit_first_rate.setText(str(data["gun1"]["rate"]))
            self.lineEdit_first_hit.setText(str(data["gun1"]["rate"]))
            self.lineEdit_first_number.setText(str(data["gun1"]["number"]))
            self.lineEdit_first_skill_1.setText(str(data["gun1"]["skill1"]))
            self.lineEdit_first_skill_2.setText(str(data["gun1"]["skill2"]))
            self.lineEdit_first_favor.setText(str(data["gun1"]["favor"]))
            self.lineEdit_first_position.setText("준비중")

            self.lineEdit_second_name.setText(str(data["gun2"]["gun_id"]))
            self.lineEdit_second_level.setText(str(data["gun2"]["gun_level"]))
            self.lineEdit_second_hp.setText(str(data["gun2"]["life"]))
            self.lineEdit_second_pow.setText(str(data["gun2"]["pow"]))
            self.lineEdit_second_dodge.setText(str(data["gun2"]["dodge"]))
            self.lineEdit_second_rate.setText(str(data["gun2"]["rate"]))
            self.lineEdit_second_hit.setText(str(data["gun2"]["rate"]))
            self.lineEdit_second_number.setText(str(data["gun2"]["number"]))
            self.lineEdit_second_skill_1.setText(str(data["gun2"]["skill1"]))
            self.lineEdit_second_skill_2.setText(str(data["gun2"]["skill2"]))
            self.lineEdit_second_favor.setText(str(data["gun2"]["favor"]))
            self.lineEdit_second_position.setText("준비중")

            self.lineEdit_third_name.setText(str(data["gun3"]["gun_id"]))
            self.lineEdit_third_level.setText(str(data["gun3"]["gun_level"]))
            self.lineEdit_third_hp.setText(str(data["gun3"]["life"]))
            self.lineEdit_third_pow.setText(str(data["gun3"]["pow"]))
            self.lineEdit_third_dodge.setText(str(data["gun3"]["dodge"]))
            self.lineEdit_third_rate.setText(str(data["gun3"]["rate"]))
            self.lineEdit_third_hit.setText(str(data["gun3"]["rate"]))
            self.lineEdit_third_number.setText(str(data["gun3"]["number"]))
            self.lineEdit_third_skill_1.setText(str(data["gun3"]["skill1"]))
            self.lineEdit_third_skill_2.setText(str(data["gun3"]["skill2"]))
            self.lineEdit_third_favor.setText(str(data["gun3"]["favor"]))
            self.lineEdit_third_position.setText("준비중")

            self.lineEdit_forth_name.setText(str(data["gun4"]["gun_id"]))
            self.lineEdit_forth_level.setText(str(data["gun4"]["gun_level"]))
            self.lineEdit_forth_hp.setText(str(data["gun4"]["life"]))
            self.lineEdit_forth_pow.setText(str(data["gun4"]["pow"]))
            self.lineEdit_forth_dodge.setText(str(data["gun4"]["dodge"]))
            self.lineEdit_forth_rate.setText(str(data["gun4"]["rate"]))
            self.lineEdit_forth_hit.setText(str(data["gun4"]["rate"]))
            self.lineEdit_forth_number.setText(str(data["gun4"]["number"]))
            self.lineEdit_forth_skill_1.setText(str(data["gun4"]["skill1"]))
            self.lineEdit_forth_skill_2.setText(str(data["gun4"]["skill2"]))
            self.lineEdit_forth_favor.setText(str(data["gun4"]["favor"]))
            self.lineEdit_forth_position.setText("준비중")

            self.lineEdit_fifth_name.setText(str(data["gun5"]["gun_id"]))
            self.lineEdit_fifth_level.setText(str(data["gun5"]["gun_level"]))
            self.lineEdit_fifth_hp.setText(str(data["gun5"]["life"]))
            self.lineEdit_fifth_pow.setText(str(data["gun5"]["pow"]))
            self.lineEdit_fifth_dodge.setText(str(data["gun5"]["dodge"]))
            self.lineEdit_fifth_rate.setText(str(data["gun5"]["rate"]))
            self.lineEdit_fifth_hit.setText(str(data["gun5"]["rate"]))
            self.lineEdit_fifth_number.setText(str(data["gun5"]["number"]))
            self.lineEdit_fifth_skill_1.setText(str(data["gun5"]["skill1"]))
            self.lineEdit_fifth_skill_2.setText(str(data["gun5"]["skill2"]))
            self.lineEdit_fifth_favor.setText(str(data["gun5"]["favor"]))
            self.lineEdit_fifth_position.setText("준비중")
        except:
            pass

    def retranslateUi(self, preview):
        _translate = QtCore.QCoreApplication.translate
        preview.setWindowTitle(_translate("preview", "미리보기"))
        self.first.setText(_translate("preview", "1번 인형"))
        self.first_name.setText(_translate("preview", "이름"))
        self.first_level.setText(_translate("preview", "레벨"))
        self.first_hp.setText(_translate("preview", "체력"))
        self.first_pow.setText(_translate("preview", "화력"))
        self.first_dodge.setText(_translate("preview", "회피"))
        self.first_rate.setText(_translate("preview", "사속"))
        self.first_hit.setText(_translate("preview", "명중"))
        self.first_number.setText(_translate("preview", "편제 수"))
        self.first_skill_1.setText(_translate("preview", "스킬 1 레벨"))
        self.first_skill_2.setText(_translate("preview", "스킬 2 레벨"))
        self.first_favor.setText(_translate("preview", "호감도"))
        self.first_position.setText(_translate("preview", "진형위치(키패드)"))
        self.second.setText(_translate("preview", "2번 인형"))
        self.second_name.setText(_translate("preview", "이름"))
        self.second_level.setText(_translate("preview", "레벨"))
        self.second_hp.setText(_translate("preview", "체력"))
        self.second_pow.setText(_translate("preview", "명중"))
        self.second_dodge.setText(_translate("preview", "회피"))
        self.second_rate.setText(_translate("preview", "사속"))
        self.second_hit.setText(_translate("preview", "명중"))
        self.second_number.setText(_translate("preview", "편제 수"))
        self.second_skill_1.setText(_translate("preview", "스킬 1 레벨"))
        self.second_skill_2.setText(_translate("preview", "스킬 2 레벨"))
        self.second_favor.setText(_translate("preview", "호감도"))
        self.second_position.setText(_translate("preview", "진형위치(키패드)"))
        self.third.setText(_translate("preview", "3번 인형"))
        self.third_name.setText(_translate("preview", "이름"))
        self.third_level.setText(_translate("preview", "레벨"))
        self.third_hp.setText(_translate("preview", "체력"))
        self.third_pow.setText(_translate("preview", "화력"))
        self.third_dodge.setText(_translate("preview", "회피"))
        self.third_rate.setText(_translate("preview", "사속"))
        self.third_hit.setText(_translate("preview", "명중"))
        self.third_number.setText(_translate("preview", "편제 수"))
        self.third_skill_1.setText(_translate("preview", "스킬 1 레벨"))
        self.third_skill_2.setText(_translate("preview", "스킬 2 레벨"))
        self.third_favor.setText(_translate("preview", "호감도"))
        self.third_position.setText(_translate("preview", "진형위치(키패드)"))
        self.forth.setText(_translate("preview", "4번 인형"))
        self.forth_name.setText(_translate("preview", "이름"))
        self.forth_level.setText(_translate("preview", "레벨"))
        self.forth_hp.setText(_translate("preview", "체력"))
        self.forth_pow.setText(_translate("preview", "화력"))
        self.forth_dodge.setText(_translate("preview", "회피"))
        self.forth_rate.setText(_translate("preview", "사속"))
        self.forth_hit.setText(_translate("preview", "명중"))
        self.forth_number.setText(_translate("preview", "편제 수"))
        self.forth_skill_1.setText(_translate("preview", "스킬 1 레벨"))
        self.forth_skill_2.setText(_translate("preview", "스킬 2 레벨"))
        self.forth_favor.setText(_translate("preview", "호감도"))
        self.forth_position.setText(_translate("preview", "진형위치(키패드)"))
        self.fifth.setText(_translate("preview", "5번 인형"))
        self.fifth_name.setText(_translate("preview", "이름"))
        self.fifth_level.setText(_translate("preview", "레벨"))
        self.fifth_hp.setText(_translate("preview", "체력"))
        self.fifth_pow.setText(_translate("preview", "화력"))
        self.fifth_dodge.setText(_translate("preview", "회피"))
        self.fifth_rate.setText(_translate("preview", "사속"))
        self.fifth_hit.setText(_translate("preview", "명중"))
        self.fifth_number.setText(_translate("preview", "편제 수"))
        self.fifth_skill_1.setText(_translate("preview", "스킬 1 레벨"))
        self.fifth_skill_2.setText(_translate("preview", "스킬 2 레벨"))
        self.fifth_favor.setText(_translate("preview", "호감도"))
        self.fifth_position.setText(_translate("preview", "진형위치(키패드)"))
        self.setting.setText(_translate("preview", "설정"))
        self.saveBtn.setText(_translate("preview", "저장"))
        self.cancelBtn.setText(_translate("preview", "종료"))
        self.menufile.setTitle(_translate("preview", "파일"))
        self.actionload.setText(_translate("preview", "불러오기"))
        self.actionsave.setText(_translate("preview", "저장"))


def saveBtn_clicked(self):
    LoadandSave.save(data)
    saveMessage.SaveMessage()
def cancelBtn_clicked(self):
    exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    preview = QtWidgets.QMainWindow()
    ui = Ui_preview()
    ui.setupUi(preview)
    preview.show()
    sys.exit(app.exec_())


